name: Deploy to S3

on:
  push:
    branches:
      - main  # Change this to the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      
        with:
          args: --acl public-read --follow-symlicks --delete
        env: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-east-1  # Replace <your-region> with your AWS region (e.g., us-east-1)
      - name: Deploy to S3 
        run: |
          aws s3 sync . s3://portfolio-abdull --delete --exclude ".git/*"
          echo "Sync completed"

      -
